version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL = "postgresql+psycopg://eoinoreilly:inscribe24@db:5432/pg-db-inscribe-test"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: eoinoreilly
      POSTGRES_PASSWORD: inscribe24
      POSTGRES_DB: pg-db-inscribe-test
    ports:
      - "5432:5432"

